version: "3.9"

services:
  reportes:
    build: .
    container_name: ms-reportes
    env_file:
      - .env
    ports:
      - "8004:8004"      # host:container â†’ http://localhost:8004
    depends_on:
      - mongo-reportes
    networks:
      - reportes_net

  mongo-reportes:
    image: mongo:7
    container_name: mongo_reportes
    volumes:
      - mongo_reportes_data:/data/db
    networks:
      - reportes_net

networks:
  reportes_net:

volumes:
  mongo_reportes_data:
