version: "3.8"

services:
  seguridad:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_seguridad
    restart: always
    ports:
      - "8001:80"       # http://localhost:8001
    volumes:
      - .:/var/www/html
    depends_on:
      - db_seguridad
    environment:
      - DB_HOST=db_seguridad
      - DB_PORT=3306
      - DB_DATABASE=microservicio-seguridad
      - DB_USERNAME=root
      - DB_PASSWORD=
    networks:
      - seguridad_net

  db_seguridad:
    image: mysql:8.0
    container_name: mysql_seguridad
    restart: always
    ports:
      - "3308:3306"     # si luego quieres conectarte desde host
    environment:
      MYSQL_DATABASE: microservicio-seguridad
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_seguridad_data:/var/lib/mysql
    networks:
      - seguridad_net

networks:
  seguridad_net:

volumes:
  db_seguridad_data:
